import { useState, useEffect } from "react";
import { Button } from "@/components/ui/button";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import { Badge } from "@/components/ui/badge";
import { motion, AnimatePresence } from "framer-motion";
import { Plus, Loader2 } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { useToast } from "@/hooks/use-toast";

interface Collaborator {
  name: string;
  username: string;
  role: string;
  avatar: string;
  lastActive: string;
  status: "active" | "idle" | "offline";
}

interface TeamActivity {
  text: string;
  time: string;
}

const statusColors: Record<string, string> = {
  active: "bg-success",
  idle: "bg-warning",
  offline: "bg-muted-foreground/30",
};

const CollaboratorsPage = () => {
  const [showAdd, setShowAdd] = useState(false);
  const [collaborators, setCollaborators] = useState<Collaborator[]>([]);
  const [teamActivity, setTeamActivity] = useState<TeamActivity[]>([]);
  const [loading, setLoading] = useState(true);
  const { toast } = useToast();

  useEffect(() => {
    const fetchCollaborations = async () => {
      try {
        const { data: { session } } = await supabase.auth.getSession();
        if (!session) {
          setLoading(false);
          return;
        }

        const token = localStorage.getItem('github_token');
        if (!token) {
          toast({
            title: "Access Token Missing",
            description: "Please sign in again to fetch team members.",
            variant: "destructive"
          });
          setLoading(false);
          return;
        }

        const username = session.user.user_metadata?.preferred_username || session.user.user_metadata?.user_name;
        const headers = { 
          Authorization: `Bearer ${token}`,
          Accept: "application/vnd.github.v3+json"
        };

        // 1. Fetch Top 10 recently updated repos we are part of
        const reposRes = await fetch("https://api.github.com/user/repos?sort=updated&per_page=10&affiliation=owner,collaborator,organization_member", { headers });
        if (!reposRes.ok) throw new Error("Failed to fetch repos");
        const repos = await reposRes.json();

        // 2. Fetch Contributors for those repos concurrently
        const uniqueContributors = new Map();
        await Promise.all(
          repos.map(async (repo: any) => {
            try {
              if (repo.contributors_url) {
                const contRes = await fetch(repo.contributors_url, { headers });
                if (!contRes.ok) return;
                const contributors = await contRes.json();
                
                if (Array.isArray(contributors)) {
                  for (const c of contributors) {
                    if (c.login === username) continue; // Skip displaying self
                    
                    if (!uniqueContributors.has(c.login)) {
                      uniqueContributors.set(c.login, {
                        name: c.login,
                        username: c.login,
                        role: repo.owner.login === c.login ? "Owner" : "Contributor",
                        avatar: c.avatar_url,
                        lastActive: "Active lately",
                        status: "active",
                        contributions: c.contributions
                      });
                    } else {
                      const existing = uniqueContributors.get(c.login);
                      existing.contributions += c.contributions;
                      // Update role to Owner if they own any of the repos
                      if (repo.owner.login === c.login) existing.role = "Owner";
                    }
                  }
                }
              }
            } catch (e) { 
              console.error("Error fetching contributors for repo", repo.name, e); 
            }
          })
        );

        // Sort by total contributions and keep top 15
        const finalContributors = Array.from(uniqueContributors.values())
          .sort((a, b) => b.contributions - a.contributions)
          .slice(0, 15);
        
        setCollaborators(finalContributors);

        // 3. Fetch Team Activity (Received Events - which are events generated by followers/collaborators)
        const eventsRes = await fetch(`https://api.github.com/users/${username}/received_events?per_page=20`, { headers });
        if (eventsRes.ok) {
          const events = await eventsRes.json();
          const parsedActivities = events
            .filter((event: any) => event.actor.login !== username) // Only show others' activity
            .map((event: any) => {
              let text = "";
              if (event.type === "PushEvent") text = `${event.actor.login} pushed to ${event.repo.name}`;
              else if (event.type === "PullRequestEvent") text = `${event.actor.login} ${event.payload.action} PR on ${event.repo.name}`;
              else if (event.type === "IssuesEvent") text = `${event.actor.login} ${event.payload.action} issue on ${event.repo.name}`;
              else if (event.type === "IssueCommentEvent") text = `${event.actor.login} commented on ${event.repo.name}`;
              else if (event.type === "CreateEvent") text = `${event.actor.login} created ${event.payload.ref_type} on ${event.repo.name}`;
              else if (event.type === "WatchEvent") text = `${event.actor.login} starred ${event.repo.name}`;
              else if (event.type === "ForkEvent") text = `${event.actor.login} forked ${event.repo.name}`;
              else text = `${event.actor.login} triggered ${event.type.replace('Event', '')} on ${event.repo.name}`;
            
              const timeOptions: Intl.DateTimeFormatOptions = { month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit' };
              return {
                text,
                time: new Date(event.created_at).toLocaleDateString(undefined, timeOptions)
              };
            });
          
          setTeamActivity(parsedActivities.slice(0, 10)); // keep last 10 entries clean
        }
      } catch (err) {
        console.error("Collaboration fetch error:", err);
      } finally {
        setLoading(false);
      }
    };

    fetchCollaborations();
  }, [toast]);

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold text-foreground">Collaborators</h1>
          <p className="text-muted-foreground">Team members automatically mapped from your active GitHub repositories.</p>
        </div>
        <Button className="gradient-primary text-primary-foreground border-0 gap-2" onClick={() => setShowAdd(!showAdd)}>
          <Plus className="h-4 w-4" /> Add Collaborator
        </Button>
      </div>

      <AnimatePresence>
        {showAdd && (
          <motion.div
            initial={{ opacity: 0, height: 0 }}
            animate={{ opacity: 1, height: "auto" }}
            exit={{ opacity: 0, height: 0 }}
            className="rounded-xl border border-border bg-card p-5 overflow-hidden"
          >
            <label className="text-sm font-medium text-card-foreground mb-2 block">Enter GitHub username</label>
            <div className="flex gap-3">
              <input
                type="text"
                placeholder="github-username"
                className="flex-1 h-10 rounded-lg bg-secondary px-4 text-sm text-foreground placeholder:text-muted-foreground border-0 outline-none focus:ring-2 focus:ring-primary/20"
              />
              <Button className="gradient-primary text-primary-foreground border-0">Invite</Button>
            </div>
          </motion.div>
        )}
      </AnimatePresence>

      <div className="flex flex-col lg:flex-row gap-6">
        <div className="flex-1 space-y-4">
          {loading ? (
            <div className="flex flex-col items-center justify-center py-12 text-muted-foreground bg-card rounded-xl border border-border">
              <Loader2 className="h-8 w-8 animate-spin mb-4" />
              <p>Analyzing cross-repo collaborators...</p>
            </div>
          ) : collaborators.length === 0 ? (
            <div className="flex flex-col items-center justify-center py-12 text-muted-foreground bg-card rounded-xl border border-border">
              <p>No active collaborators found on your recent repositories.</p>
            </div>
          ) : (
            <div className="grid gap-4 sm:grid-cols-2">
              {collaborators.map((collab, i) => (
                <motion.div
                  key={collab.username}
                  initial={{ opacity: 0, y: 10 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ delay: i * 0.05 }}
                  className="rounded-xl border border-border bg-card p-5 hover:shadow-md hover:border-primary/20 transition-all"
                >
                  <div className="flex items-center gap-4">
                    <div className="relative">
                      <Avatar className="h-12 w-12 border border-border">
                        <AvatarImage src={collab.avatar} />
                        <AvatarFallback className="bg-primary text-primary-foreground">{collab.name.substring(0, 2).toUpperCase()}</AvatarFallback>
                      </Avatar>
                      <div className={`absolute -bottom-0.5 -right-0.5 h-3.5 w-3.5 rounded-full border-2 border-card ${statusColors[collab.status]}`} />
                    </div>
                    <div className="flex-1 min-w-0">
                      <div className="flex items-center gap-2 mb-0.5">
                        <span className="text-base font-semibold text-card-foreground truncate">{collab.name}</span>
                        <Badge variant="secondary" className="text-[10px] uppercase font-bold tracking-wider">{collab.role}</Badge>
                      </div>
                      <a href={`https://github.com/${collab.username}`} target="_blank" rel="noopener noreferrer" className="text-sm text-muted-foreground hover:text-primary transition-colors">
                        @{collab.username}
                      </a>
                      <p className="text-xs text-muted-foreground mt-1.5 flex items-center gap-1.5">
                        <span className="h-1.5 w-1.5 rounded-full bg-success opacity-75"></span>
                        {collab.lastActive}
                      </p>
                    </div>
                  </div>
                </motion.div>
              ))}
            </div>
          )}
        </div>

        {/* Team activity sidebar */}
        <div className="w-full lg:w-96 shrink-0">
          <div className="rounded-xl border border-border bg-card sticky top-4 overflow-hidden">
            <div className="border-b border-border px-6 py-4 bg-secondary/30">
              <h2 className="text-sm uppercase tracking-wider font-bold text-card-foreground">Global Team Activity</h2>
              <p className="text-xs text-muted-foreground mt-1">Live from your GitHub received events</p>
            </div>
            <div className="divide-y divide-border">
              {loading ? (
                <div className="py-12 flex justify-center"><Loader2 className="h-6 w-6 animate-spin text-muted-foreground" /></div>
              ) : teamActivity.length === 0 ? (
                <div className="py-12 text-center text-sm text-muted-foreground px-4">No recent team activity found.</div>
              ) : (
                teamActivity.map((item, i) => (
                  <motion.div 
                    key={i} 
                    initial={{ opacity: 0, x: 10 }}
                    animate={{ opacity: 1, x: 0 }}
                    transition={{ delay: i * 0.05 }}
                    className="flex flex-col px-6 py-4 hover:bg-secondary/20 transition-colors"
                  >
                    <p className="text-sm text-card-foreground leading-relaxed">{item.text}</p>
                    <span className="text-xs text-muted-foreground mt-1.5">{item.time}</span>
                  </motion.div>
                ))
              )}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default CollaboratorsPage;
